<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <AvaloniaUseCompiledBindings>true</AvaloniaUseCompiledBindings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.2.1" />
        <PackageReference Include="Avalonia.Controls.DataGrid" Version="11.2.1" />
        <PackageReference Include="Avalonia.Desktop" Version="11.2.1" />
        <PackageReference Include="Avalonia.ReactiveUI" Version="11.2.1" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.2.1" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="11.2.1" />

        <PackageReference Include="ReactiveUI" Version="20.1.1" />
        <PackageReference Include="Npgsql" Version="7.0.6" />
        <PackageReference Include="Microsoft.Extensions.Configuration" Version="7.0.0" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="7.0.0" />
    </ItemGroup>

    <ItemGroup>
        <None Update="appsettings.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

    <ItemGroup>
        <AdditionalFiles Include="Views\LoginView.axaml" />
        <AdditionalFiles Include="Views\MainWindow.axaml" />
    </ItemGroup>
</Project>
