SELECT * FROM Furnizori
SELECT * FROM Categorie
SELECT * FROM Produse
SELECT * FROM Depozite
SELECT * FROM Manageri
SELECT * FROM Departamente
SELECT * FROM ProduseDepozite
SELECT * FROM Angajati
SELECT * FROM Clienti
SELECT * FROM Comenzi