spring.application.name=laboratorREST
spring.datasource.url=jdbc:postgresql://localhost:5432/laborator_rest
spring.datasource.username=postgres
spring.datasource.password=antimagu
spring.jpa.hibernate.ddl-auto=update
spring.websocket.enabled=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect